### ISSUE TITLE
dependency 0.9.1 can't be resolved

### ISSUE THREAD

**Issue by jeantuffier** [Kotlin/anko#309] opened 2017-02-02 09:07 UTC
I'm trying to compile the anko-test project (https://github.com/yanex/anko-example.git) but gradle can't resolve the dependency to the library : 
```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find org.jetbrains.anko:anko-sdk15:0.9.1.
     Required by:
         anko-example:app:unspecified
```

**Comment by sindrenm** [comment] 2017-02-02 09:33
This is probably a duplicate of #308. :wink:

**Comment by dokinkon** [comment] 2017-02-05 13:51
I can resolve the dependency by typing org.jetbrains.anko:anko-sdk15:**0.9**

**Comment by yperess** [comment] 2017-02-06 17:37
Looking at jcenter they never pushed 0.9.1

https://jcenter.bintray.com/org/jetbrains/anko/anko-sdk23/

**Comment by yanex** [comment] 2017-02-09 18:13
See also #313.

**Closed by yanex** 2017-02-09 18:13 UTC

**Comment by sindrenm** [comment] 2017-02-09 20:31
Nice, @yanex!
