### ISSUE TITLE
Anko DSL Preview Plugin can not work in androidStudo 2.2.3

### ISSUE THREAD

**Issue by s949492225** [Kotlin/anko#293] opened 2017-01-03 10:12 UTC
![image](https://cloud.githubusercontent.com/assets/7496283/21604784/23f4d0f4-d1e0-11e6-8b1e-9da8b46a18c4.png)

**Comment by pinkApple** [comment] 2017-01-03 10:14
not support 2.2.3, you should disable the plugin.

**Comment by bentolor** [comment] 2017-01-15 16:05
Duplicate of #202

**Closed** 2017-01-19 08:35 UTC

**Comment by blazeur** [comment] 2017-03-24 21:02
Hi,
I have the same problem on Android 2.3 with anko 0.9b.
I don't find issue

**Comment by piotrek1543** [comment] 2017-03-24 22:02
@blazeur Anko is not compatible with all 2.1 and later Android Studio versions.
