### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getActivity() by toast("message") 

### ISSUE THREAD

**Issue by dEn13L** [Kotlin/anko#328] opened 2017-02-23 06:16 UTC
Next error message shows while I call `toast("Message")` method in fragment

`java.lang.NoSuchMethodError: No virtual method getActivity()Landroid/app/Activity; in class Landroid/support/v4/app/Fragment; or its super classes (declaration of 'android.support.v4.app.Fragment' appears in name-of-the-file-classes.dex)`

Kotlin 1.1.0-rc-91
Anko v0.9.1
Android Studio 2.3 RC

According closed task #311 I used 

`override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? = FragmentUi<Fragment>().createView(AnkoContext.create(activity, this)) }`

but error still happens

**Comment by Nyest** [comment] 2017-03-02 06:37
getActivity().toast("Message")

I will used this when i call toast in fragment

**Comment by julianostarek** [comment] 2017-03-06 15:19
Same here, this prevents me from using 0.9.1

**Comment by yanex** [comment] 2017-03-06 19:08
Duplicate of #311.

**Closed by yanex** 2017-03-06 19:08 UTC
