### ISSUE TITLE
When setting a style as a button's theme, background attribute is not applied

### ISSUE THREAD

**Issue by CorayThan** [Kotlin/anko#305] opened 2017-01-26 23:25 UTC
I was passing a button style as the resource for the theme of a button in Anko's DSL, and noticed the background set in the theme was not applied. If I set the background directly on the button, then it worked.

This doesn't work:

```
    <style name="StandardButton">
        <item name="android:background">@drawable/button_background</item>
    </style>
```

`button(theme = R.style.StandardButton)`

But this does:

```
button {
    background = ResourcesCompat.getDrawable(resources, R.drawable.button_background, null)
}
```

**Comment by hannesstruss** [comment] 2017-02-05 13:04
This happens for the [following reason](https://github.com/Kotlin/anko/issues/16#issuecomment-277295486):

> Resolving the attr does not actually work in all cases. Example:
>
> `button("My Button", theme = attrStyle(R.attr.buttonBarButtonStyle))`
>
> will not apply the correct background, since the one-argument constructor of `Button` that Anko uses calls through to the three-argument constructor with a default value for `int defStyleAttr` which overrides the button background with the default.
> 
> While working in some cases, the theme support of Anko 0.9 is not a full replacement for the `style` XML attribute. Can we reopen this issue?

**Comment by yanex** [comment] 2017-05-03 19:30
Duplicate of #361.

**Closed by yanex** 2017-05-03 19:30 UTC
