### ISSUE TITLE
Anko Plugin error

### ISSUE THREAD

**Issue by YZHIWEN** [Kotlin/anko#448] opened 2017-07-28 08:32 UTC
i install Anko Plugin from AS，and restart AS failed

![image](https://user-images.githubusercontent.com/16757600/28709261-25501dc2-73b2-11e7-9b5f-a49bc127797e.png)

**Comment by AminRahkan** [comment] 2017-07-29 09:40
you should use android studio 3 canary version

**Comment by YZHIWEN** [comment] 2017-07-30 17:07
i use android studio 3, but still some question, such can not preview activity, can not find the preview button after restart as3

![image](https://user-images.githubusercontent.com/16757600/28755398-8d9387bc-758c-11e7-9dc2-866f7d614271.png)

**Comment by arslancharyev31** [comment] 2017-07-31 09:54
Another duplicate of #398, #414 and #421

**Comment by reflog** [comment] 2017-08-01 07:25
any news on this issue? would really like to try out Anko, but without preview it's really hard to use :(

**Comment by arslancharyev31** [comment] 2017-08-02 11:08
@reflog, I've inquired devs about the status of this library in [this thread](https://discuss.kotlinlang.org/t/whats-up-with-anko/)

**Comment by reflog** [comment] 2017-08-02 11:27
Thanks, interesting read. Basically, for the near future Anko DSL is not for production use I fear. But I hope it will be one day, really rooting for it :)

**Comment by arslancharyev31** [comment] 2017-08-02 14:42
@reflog, Well, basically any library with version 0.x is not suited for production use. However, in this case, I suppose the major factor turning devs away from this outstanding library, for now, is its lack of documentation and previewing tools accompanied by the limited amount of resources invested by maintainers.

**Closed** 2017-11-14 16:43 UTC
