### ISSUE TITLE
Does Anko DSL Preview Plugin supports IntelliJ 2016.3?

### ISSUE THREAD

**Issue by GoopyTylenol** [Kotlin/anko#276] opened 2016-12-01 12:09 UTC
Hello, I am using IDEA 2016.3 Ver,
It throws Incompatible error when I try to install dsl preview plugin.

When it supports 2016.3 version??

**Comment by baoxin** [comment] 2016-12-12 08:22
I tried before, can't use

**Comment by NeverwinterMoon** [comment] 2016-12-27 07:19
I just recently discovered Anko and was very excited about it, until I found out that preview plugin doesn't work with IDEA 2016.3. Been using that version from day one and definitely not about to go to older one.  

It's sad to see that plugin is still not supported for IDEA released over a month ago (November 22), especially considering that Anko is made by the same company as IDE itself...

**Comment by bentolor** [comment] 2017-01-15 16:06
Duplicate of #202

**Comment by yanex** [comment] 2017-02-10 19:30
See also #314.

**Closed by yanex** 2017-02-10 19:30 UTC
