### ISSUE TITLE
startActivity breaks when moving from 0.9 to 0.9.1

### ISSUE THREAD

**Issue by andre-artus** [Kotlin/anko#322] opened 2017-02-20 06:12 UTC
I just spent hours trying to determine why all of a sudden I'm getting errors when trying to start an activity, it turns out that in moving from 0.9 to 0.9.1 something changed in Anko that causes the problem. I was not expecting a minor version change to be a breaking change.

When starting an activity with `startActivity<T>` it results in this error when compiled with 0.9.1
```
 java.lang.NoSuchMethodError: No virtual method getActivity()Landroid/app/Activity; in class Landroid/support/v4/app/Fragment; or its super classes
```

When I revert back to 0.9 it work as expected.

**Comment by yanex** [comment] 2017-02-20 17:43
Duplicate of #311.

**Closed by yanex** 2017-02-20 17:43 UTC
